export interface Vehicle {
	type: string,
	make: string,
	model: string,
	body: string,
	status: string,
	doors: number,
	fuel: string,
	seats: number,
	roof: string,
	colour: string,
	comment: string,
	image_url: string,
	year: number,
}