# This file should contain all the record creation needed to seed the database
# with its default values.
# The data can then be loaded with the rails db:seed command (or created
# alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create(
#     [{ name: 'Star Wars' }, { name: 'Lord of the Rings' }]
#   )
#   Character.create(name: 'Luke', movie: movies.first)

User.create(
    first_name: 'John',
    last_name: 'Doe',
    email: 'smartadmin@example.org',
    password: 'smartadmin',
    admin: true
)
User.create(
    first_name: 'Average',
    last_name: 'User',
    email: 'smartuser@example.org',
    password: 'smartuser',
    admin: false
)
Setting.create(
    theme: 'smart-style-1',
    new_user_registration: true
)
VehicleType.create(
    [
        {name: 'Személyautó'},
        {name: 'Kishaszonjármű'},
        {name: 'Haszonjármű'},
        {name: 'Munkagép'},
        {name: 'Motorkerékpár'},
        {name: 'Autóbusz'}
    ])

#TODO: Kishaszongépjármű és személyautó márkák már beletöltve.
VehicleBrand.create(
    [
        {name: 'ABARTH', vehicle_type_id: 1},
        {name: 'ACURA', vehicle_type_id: 1},
        {name: 'ADLER', vehicle_type_id: 1},
        {name: 'AIXAM', vehicle_type_id: 1},
        {name: 'ALEKO', vehicle_type_id: 1},
        {name: 'ALFA ROMEO', vehicle_type_id: 1},
        {name: 'ALPINA', vehicle_type_id: 1},
        {name: 'AMC', vehicle_type_id: 1},
        {name: 'ARO', vehicle_type_id: 1},
        {name: 'ASIA', vehicle_type_id: 1},
        {name: 'ASTON MARTIN', vehicle_type_id: 1},
        {name: 'AUDI', vehicle_type_id: 1},
        {name: 'AUSTIN', vehicle_type_id: 1},
        {name: 'AUSTIN MORRIS', vehicle_type_id: 1},
        {name: 'AUTOBIANCHI', vehicle_type_id: 1},
        {name: 'BAJAJ', vehicle_type_id: 1},
        {name: 'BARKAS', vehicle_type_id: 1},
        {name: 'BENTLEY', vehicle_type_id: 1},
        {name: 'BMW', vehicle_type_id: 1},
        {name: 'BRILLIANCE (ZHONGHUA)', vehicle_type_id: 1},
        {name: 'BUICK', vehicle_type_id: 1},
        {name: 'CADILLAC', vehicle_type_id: 1},
        {name: 'CHEVROLET', vehicle_type_id: 1},
        {name: 'CHRYSLER', vehicle_type_id: 1},
        {name: 'CITROEN', vehicle_type_id: 1},
        {name: 'DACIA', vehicle_type_id: 1},
        {name: 'DAEWOO', vehicle_type_id: 1},
        {name: 'DAIHATSU', vehicle_type_id: 1},
        {name: 'DAIMLER', vehicle_type_id: 1},
        {name: 'DATSUN', vehicle_type_id: 1},
        {name: 'DODGE', vehicle_type_id: 1},
        {name: 'DR', vehicle_type_id: 1},
        {name: 'DS', vehicle_type_id: 1},
        {name: 'EGYÉB', vehicle_type_id: 1},
        {name: 'EGYEDI', vehicle_type_id: 1},
        {name: 'ELECTROAUTO', vehicle_type_id: 1},
        {name: 'EXCALIBUR', vehicle_type_id: 1},
        {name: 'FERRARI', vehicle_type_id: 1},
        {name: 'FIAT', vehicle_type_id: 1},
        {name: 'FISKER', vehicle_type_id: 1},
        {name: 'FORD', vehicle_type_id: 1},
        {name: 'GAZ', vehicle_type_id: 1},
        {name: 'GEO', vehicle_type_id: 1},
        {name: 'GMC', vehicle_type_id: 1},
        {name: 'GREAT WALL', vehicle_type_id: 1},
        {name: 'GRECAV', vehicle_type_id: 1},
        {name: 'HONDA', vehicle_type_id: 1},
        {name: 'HUDSON', vehicle_type_id: 1},
        {name: 'HUMMER', vehicle_type_id: 1},
        {name: 'HYUNDAI', vehicle_type_id: 1},
        {name: 'INFINITI', vehicle_type_id: 1},
        {name: 'ISUZU', vehicle_type_id: 1},
        {name: 'IVECO', vehicle_type_id: 1},
        {name: 'JAGUAR', vehicle_type_id: 1},
        {name: 'JDM', vehicle_type_id: 1},
        {name: 'JEEP', vehicle_type_id: 1},
        {name: 'KIA', vehicle_type_id: 1},
        {name: 'LADA', vehicle_type_id: 1},
        {name: 'LAMBORGHINI', vehicle_type_id: 1},
        {name: 'LANCIA', vehicle_type_id: 1},
        {name: 'LAND ROVER', vehicle_type_id: 1},
        {name: 'LEVC', vehicle_type_id: 1},
        {name: 'LEXUS', vehicle_type_id: 1},
        {name: 'LIGIER', vehicle_type_id: 1},
        {name: 'LINCOLN', vehicle_type_id: 1},
        {name: 'LONDON', vehicle_type_id: 1},
        {name: 'LOTUS', vehicle_type_id: 1},
        {name: 'LTI (CARBODIES)', vehicle_type_id: 1},
        {name: 'LUAZ', vehicle_type_id: 1},
        {name: 'MAHINDRA', vehicle_type_id: 1},
        {name: 'MAN', vehicle_type_id: 1},
        {name: 'MARUTI', vehicle_type_id: 1},
        {name: 'MASERATI', vehicle_type_id: 1},
        {name: 'MATRA', vehicle_type_id: 1},
        {name: 'MAZDA', vehicle_type_id: 1},
        {name: 'MCLAREN', vehicle_type_id: 1},
        {name: 'MERCEDES-AMG', vehicle_type_id: 1},
        {name: 'MERCEDES-BENZ', vehicle_type_id: 1},
        {name: 'MERCEDES-MAYBACH', vehicle_type_id: 1},
        {name: 'MERCURY', vehicle_type_id: 1},
        {name: 'MG', vehicle_type_id: 1},
        {name: 'MICROCAR', vehicle_type_id: 1},
        {name: 'MINI', vehicle_type_id: 1},
        {name: 'MITSUBISHI', vehicle_type_id: 1},
        {name: 'MORRIS', vehicle_type_id: 1},
        {name: 'MOSZKVICS', vehicle_type_id: 1},
        {name: 'NISSAN', vehicle_type_id: 1},
        {name: 'NSU', vehicle_type_id: 1},
        {name: 'NYSA', vehicle_type_id: 1},
        {name: 'OLDSMOBILE', vehicle_type_id: 1},
        {name: 'OPEL', vehicle_type_id: 1},
        {name: 'PEUGEOT', vehicle_type_id: 1},
        {name: 'PIAGGIO', vehicle_type_id: 1},
        {name: 'PLYMOUTH', vehicle_type_id: 1},
        {name: 'POLSKI FIAT', vehicle_type_id: 1},
        {name: 'PONTIAC', vehicle_type_id: 1},
        {name: 'PORSCHE', vehicle_type_id: 1},
        {name: 'PROTON', vehicle_type_id: 1},
        {name: 'PULI', vehicle_type_id: 1},
        {name: 'RELIANT', vehicle_type_id: 1},
        {name: 'RENAULT', vehicle_type_id: 1},
        {name: 'REPLIKA', vehicle_type_id: 1},
        {name: 'ROLLS-ROYCE', vehicle_type_id: 1},
        {name: 'ROVER', vehicle_type_id: 1},
        {name: 'SAAB', vehicle_type_id: 1},
        {name: 'SATURN', vehicle_type_id: 1},
        {name: 'SEAT', vehicle_type_id: 1},
        {name: 'SIMCA', vehicle_type_id: 1},
        {name: 'SKODA', vehicle_type_id: 1},
        {name: 'SMART', vehicle_type_id: 1},
        {name: 'SSANGYONG', vehicle_type_id: 1},
        {name: 'STEYR PUCH', vehicle_type_id: 1},
        {name: 'SUBARU', vehicle_type_id: 1},
        {name: 'SUZUKI', vehicle_type_id: 1},
        {name: 'TALBOT', vehicle_type_id: 1},
        {name: 'TATA', vehicle_type_id: 1},
        {name: 'TATRA', vehicle_type_id: 1},
        {name: 'TAVRIA', vehicle_type_id: 1},
        {name: 'TESLA', vehicle_type_id: 1},
        {name: 'TOYOTA', vehicle_type_id: 1},
        {name: 'TRABANT', vehicle_type_id: 1},
        {name: 'TRIUMPH', vehicle_type_id: 1},
        {name: 'UAZ', vehicle_type_id: 1},
        {name: 'VAUXHALL', vehicle_type_id: 1},
        {name: 'VELOREX', vehicle_type_id: 1},
        {name: 'VERSENYAUTÓ', vehicle_type_id: 1},
        {name: 'VOLGA', vehicle_type_id: 1},
        {name: 'VOLKSWAGEN', vehicle_type_id: 1},
        {name: 'VOLVO', vehicle_type_id: 1},
        {name: 'WARSZAWA', vehicle_type_id: 1},
        {name: 'WARTBURG', vehicle_type_id: 1},
        {name: 'WOLSELEY', vehicle_type_id: 1},
        {name: 'YUGO', vehicle_type_id: 1},
        {name: 'ZAPOROZSEC', vehicle_type_id: 1},
        {name: 'ZASTAVA', vehicle_type_id: 1},
        {name: 'ARO', vehicle_type_id: 2},
        {name: 'BARKAS', vehicle_type_id: 2},
        {name: 'BEDFORD', vehicle_type_id: 2},
        {name: 'BIRDIE', vehicle_type_id: 2},
        {name: 'CHEVROLET', vehicle_type_id: 2},
        {name: 'CHRYSLER', vehicle_type_id: 2},
        {name: 'CITROEN', vehicle_type_id: 2},
        {name: 'DACIA', vehicle_type_id: 2},
        {name: 'DAEWOO', vehicle_type_id: 2},
        {name: 'DAIHATSU', vehicle_type_id: 2},
        {name: 'DODGE', vehicle_type_id: 2},
        {name: 'EGYÉB', vehicle_type_id: 2},
        {name: 'ELECTROAUTO', vehicle_type_id: 2},
        {name: 'FIAT', vehicle_type_id: 2},
        {name: 'FORD', vehicle_type_id: 2},
        {name: 'GAZ', vehicle_type_id: 2},
        {name: 'GMC', vehicle_type_id: 2},
        {name: 'GOUPIL', vehicle_type_id: 2},
        {name: 'GRILLO', vehicle_type_id: 2},
        {name: 'HONDA', vehicle_type_id: 2},
        {name: 'HYUNDAI', vehicle_type_id: 2},
        {name: 'ISUZU', vehicle_type_id: 2},
        {name: 'IVECO', vehicle_type_id: 2},
        {name: 'JIANGXI', vehicle_type_id: 2},
        {name: 'KIA', vehicle_type_id: 2},
        {name: 'LADA', vehicle_type_id: 2},
        {name: 'LAND ROVER', vehicle_type_id: 2},
        {name: 'LEXUS', vehicle_type_id: 2},
        {name: 'LUBLIN', vehicle_type_id: 2},
        {name: 'MAHINDRA', vehicle_type_id: 2},
        {name: 'MAN', vehicle_type_id: 2},
        {name: 'MAZDA', vehicle_type_id: 2},
        {name: 'MEGA', vehicle_type_id: 2},
        {name: 'MELEX', vehicle_type_id: 2},
        {name: 'MERCEDES-BENZ', vehicle_type_id: 2},
        {name: 'MICRO-VETT', vehicle_type_id: 2},
        {name: 'MINI', vehicle_type_id: 2},
        {name: 'MITSUBISHI', vehicle_type_id: 2},
        {name: 'MULTICAR', vehicle_type_id: 2},
        {name: 'NISSAN', vehicle_type_id: 2},
        {name: 'OPEL', vehicle_type_id: 2},
        {name: 'PEUGEOT', vehicle_type_id: 2},
        {name: 'PIAGGIO', vehicle_type_id: 2},
        {name: 'RENAULT', vehicle_type_id: 2},
        {name: 'SEAT', vehicle_type_id: 2},
        {name: 'SKODA', vehicle_type_id: 2},
        {name: 'SSANGYONG', vehicle_type_id: 2},
        {name: 'STEYR', vehicle_type_id: 2},
        {name: 'SUZUKI', vehicle_type_id: 2},
        {name: 'TATA', vehicle_type_id: 2},
        {name: 'TOYOTA', vehicle_type_id: 2},
        {name: 'UAZ', vehicle_type_id: 2},
        {name: 'VAUXHALL', vehicle_type_id: 2},
        {name: 'VOLKSWAGEN', vehicle_type_id: 2},
        {name: 'YAMAHA', vehicle_type_id: 2},
        {name: 'ZSUK', vehicle_type_id: 2},
        {name: 'CSEPEL', vehicle_type_id: 3},
        {name: 'FORD', vehicle_type_id: 3},
        {name: 'GAZ', vehicle_type_id: 3},
        {name: 'IVECO', vehicle_type_id: 3},
        {name: 'BOBCAT', vehicle_type_id: 4},
        {name: 'CATERPILLAR', vehicle_type_id: 4},
        {name: 'FORD', vehicle_type_id: 4},
        {name: 'HUSQVARNA', vehicle_type_id: 4},
        {name: 'HONDA', vehicle_type_id: 5},
        {name: 'BMW', vehicle_type_id: 5},
        {name: 'SUZUKI', vehicle_type_id: 5},
        {name: 'VESPA', vehicle_type_id: 5},
        {name: 'FIAT', vehicle_type_id: 6},
        {name: 'FORD', vehicle_type_id: 6},
        {name: 'IKARUS', vehicle_type_id: 6},
        {name: 'IVECO', vehicle_type_id: 6},
        {name: 'ISUZU', vehicle_type_id: 6},
    ])
VehicleCategory.create(
    [
        {name: 'Tehergépjármű', vehicle_type_id: 3},
        {name: 'Kommunális gépjármű', vehicle_type_id: 3},
        {name: 'Felépítmény, tartozék, adapter', vehicle_type_id: 3},
        {name: 'Mezőgazdasági gép', vehicle_type_id: 4},
        {name: 'Építőipari gép', vehicle_type_id: 4},
        {name: 'Targonca', vehicle_type_id: 4}
    ])
VehicleBody.create(
    [
        {name: 'Buggy', vehicle_type_id: 1},
        {name: 'Cabrio', vehicle_type_id: 1},
        {name: 'Coupe', vehicle_type_id: 1},
        {name: 'Egyterű', vehicle_type_id: 1},
        {name: 'Ferdehátú', vehicle_type_id: 1},
        {name: 'Hot rod', vehicle_type_id: 1},
        {name: 'Kisbusz', vehicle_type_id: 1},
        {name: 'Kombi', vehicle_type_id: 1},
        {name: 'Mopedautó', vehicle_type_id: 1},
        {name: 'Lépcsőshátú', vehicle_type_id: 1},
        {name: 'Pickup', vehicle_type_id: 1},
        {name: 'Sedan', vehicle_type_id: 1},
        {name: 'Sport', vehicle_type_id: 1},
        {name: 'Terepjáró', vehicle_type_id: 1},
        {name: 'Városi terepjáró (crossover)', vehicle_type_id: 1},
        {name: 'Egyéb', vehicle_type_id: 1},
        {name: 'Alváz dupla kabinnal', vehicle_type_id: 2},
        {name: 'Duplakabinos autómentő', vehicle_type_id: 2},
        {name: 'Duplakabinos billenőplatós', vehicle_type_id: 2},
        {name: 'Duplakabinos darus', vehicle_type_id: 2},
        {name: 'Duplakabinos dobozos (koffer)', vehicle_type_id: 2},
        {name: 'Duplakabinos dobozos-emelőhátfalas', vehicle_type_id: 2},
        {name: 'Duplakabinos emelőkosaras', vehicle_type_id: 2},
        {name: 'Duplakabinos létrás', vehicle_type_id: 2},
        {name: 'Duplakabinos platós', vehicle_type_id: 2},
        {name: 'Duplakabinos ponyvás', vehicle_type_id: 2},
        {name: 'Duplakabinos ponyvás-emelőhátfalas', vehicle_type_id: 2},
        {name: 'Alváz szimpla kabinnal', vehicle_type_id: 2},
        {name: 'Autómentő', vehicle_type_id: 2},
        {name: 'Billenőplatós', vehicle_type_id: 2},
        {name: 'Darus', vehicle_type_id: 2},
        {name: 'Dobozos (emelőhátfalas)', vehicle_type_id: 2},
        {name: 'Dobozos (koffer)', vehicle_type_id: 2},
        {name: 'Duplakabinos élőállat-szállító', vehicle_type_id: 2},
        {name: 'Emelőkosaras', vehicle_type_id: 2},
        {name: 'Hűtős alváz', vehicle_type_id: 2},
        {name: 'Létrás', vehicle_type_id: 2},
        {name: 'Mozgóbolt, büfékocsi', vehicle_type_id: 2},
        {name: 'Platós', vehicle_type_id: 2},
        {name: 'Ponyvás', vehicle_type_id: 2},
        {name: 'Ponyvás (emelőhátfalas)', vehicle_type_id: 2},
        {name: 'ATV', vehicle_type_id: 2},
        {name: 'Darus billenőplatós', vehicle_type_id: 2},
        {name: 'Élőállat-szállító', vehicle_type_id: 2},
        {name: 'Halottas', vehicle_type_id: 2},
        {name: 'Konténeres', vehicle_type_id: 2},
        {name: 'Mentő', vehicle_type_id: 2},
        {name: 'Páncélozott pickup', vehicle_type_id: 2},
        {name: 'Pickup', vehicle_type_id: 2},
        {name: 'Duplakabinos pickup', vehicle_type_id: 2},
        {name: 'Szimplakabinos pickup', vehicle_type_id: 2},
        {name: 'Terepjáró', vehicle_type_id: 2},
        {name: 'Tűzoltó', vehicle_type_id: 2},
        {name: 'Zárt', vehicle_type_id: 2},
        {name: 'Cargo', vehicle_type_id: 2},
        {name: 'Félig ablakos', vehicle_type_id: 2},
        {name: 'Furgon', vehicle_type_id: 2},
        {name: 'Hűtős (zárt)', vehicle_type_id: 2},
        {name: 'Körbeüvegezett', vehicle_type_id: 2},
        {name: 'Van', vehicle_type_id: 2},
        {name: 'Egyéb', vehicle_type_id: 2},
        {name: 'Alváz', vehicle_type_id: 3},
        {name: 'Baromfiszállító', vehicle_type_id: 3},
        {name: 'Billencs', vehicle_type_id: 3},
        {name: 'Állattenyésztési gép', vehicle_type_id: 4},
        {name: 'Daráló', vehicle_type_id: 4},
        {name: 'Egyéb betakarító gép', vehicle_type_id: 4},
        {name: 'Erőgép', vehicle_type_id: 4},
        {name: 'Kertészeti gép', vehicle_type_id: 4},
        {name: 'Kombájn', vehicle_type_id: 4},
        {name: 'Fűnyíró', vehicle_type_id: 4},
        {name: 'Chopper', vehicle_type_id: 5},
        {name: 'Cruiser', vehicle_type_id: 5},
        {name: 'Custom', vehicle_type_id: 5},
        {name: 'Pitbike', vehicle_type_id: 5},
        {name: 'Quad', vehicle_type_id: 5},
        {name: 'Cross', vehicle_type_id: 5},
        {name: 'Enduro', vehicle_type_id: 5},
        {name: 'Oldalkocsis', vehicle_type_id: 5},
        {name: 'Robogó', vehicle_type_id: 5},
        {name: 'Állatszállító busz', vehicle_type_id: 6},
        {name: 'Emeletes busz', vehicle_type_id: 6},
        {name: 'Bisztró busz', vehicle_type_id: 6},
        {name: 'Városnéző autóbusz', vehicle_type_id: 6},
        {name: 'Turista autóbusz', vehicle_type_id: 6},
        {name: 'Városi autóbusz', vehicle_type_id: 6},
        {name: 'Mozgóbolt', vehicle_type_id: 6},
        {name: 'Mozgó szűrőállomás', vehicle_type_id: 6},
        {name: 'Minibusz', vehicle_type_id: 6},
        {name: 'Hotel busz', vehicle_type_id: 6},
    ])
VehicleCondition.create(
    [
        {name: 'Normál'},
        {name: 'Kitűnő'},
        {name: 'Megkímélt'},
        {name: 'Újszerű'},
        {name: 'Sérülésmentes'},
        {name: 'Sérült'},
        {name: 'Enyhén sérült'},
        {name: 'Eleje sérült'},
        {name: 'Hátulja sérült'},
        {name: 'Baloldala sérült'},
        {name: 'Jobboldala sérült'},
        {name: 'Hiányos'},
        {name: 'Fődarab hibás'},
        {name: 'Motorhibás'},
        {name: 'Váltóhibás'},
        {name: 'Elektronika hibás'},
        {name: 'Fékhibás'},
        {name: 'Futómű hibás'}
    ])
VehicleFuel.create(
    [
        {name: 'Benzin'},
        {name: 'Diesel'},
        {name: 'Gáz'},
        {name: 'Elektromos'},
        {name: 'Hibrid'},
    ])

