# This file should contain all the record creation needed to seed the database
# with its default values.
# The data can then be loaded with the rails db:seed command (or created
# alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create(
#     [{ name: 'Star Wars' }, { name: 'Lord of the Rings' }]
#   )
#   Character.create(name: 'Luke', movie: movies.first)

User.create(
    first_name: 'John',
    last_name: 'Doe',
    email: 'smartadmin@example.org',
    password: 'smartadmin',
    admin: true
)
User.create(
        first_name: 'Average',
        last_name: 'User',
        email: 'smartuser@example.org',
        password: 'smartuser',
        admin: false
)
Setting.create(
    theme: 'smart-style-1',
    new_user_registration: true
)
VehicleType.create([
    { name: 'Személyautó' },
    { name: 'Kishaszonjármű' },
    { name: 'Haszonjármű' },
    { name: 'Munkagép' },
    { name: 'Motorkerékpár' },
    { name: 'Autóbusz' }
])

#TODO: Kishaszongépjármű és személyautó márkák már beletöltve.
VehicleBrand.create([
    { name: 'ABARTH', vehicle_type_id: 1 },
    { name: 'ACURA', vehicle_type_id: 1 },
    { name: 'ADLER', vehicle_type_id: 1 },
    { name: 'AIXAM', vehicle_type_id: 1 },
    { name: 'ALEKO', vehicle_type_id: 1 },
    { name: 'ALFA ROMEO', vehicle_type_id: 1 },
    { name: 'ALPINA', vehicle_type_id: 1 },
    { name: 'AMC', vehicle_type_id: 1 },
    { name: 'ARO', vehicle_type_id: 1 },
    { name: 'ASIA', vehicle_type_id: 1 },
    { name: 'ASTON MARTIN', vehicle_type_id: 1 },
    { name: 'AUDI', vehicle_type_id: 1 },
    { name: 'AUSTIN', vehicle_type_id: 1 },
    { name: 'AUSTIN MORRIS', vehicle_type_id: 1 },
    { name: 'AUTOBIANCHI', vehicle_type_id: 1 },
    { name: 'BAJAJ', vehicle_type_id: 1 },
    { name: 'BARKAS', vehicle_type_id: 1 },
    { name: 'BENTLEY', vehicle_type_id: 1 },
    { name: 'BMW', vehicle_type_id: 1 },
    { name: 'BRILLIANCE (ZHONGHUA)', vehicle_type_id: 1 },
    { name: 'BUICK', vehicle_type_id: 1 },
    { name: 'CADILLAC', vehicle_type_id: 1 },
    { name: 'CHEVROLET', vehicle_type_id: 1 },
    { name: 'CHRYSLER', vehicle_type_id: 1 },
    { name: 'CITROEN', vehicle_type_id: 1 },
    { name: 'DACIA', vehicle_type_id: 1 },
    { name: 'DAEWOO', vehicle_type_id: 1 },
    { name: 'DAIHATSU', vehicle_type_id: 1 },
    { name: 'DAIMLER', vehicle_type_id: 1 },
    { name: 'DATSUN', vehicle_type_id: 1 },
    { name: 'DODGE', vehicle_type_id: 1 },
    { name: 'DR', vehicle_type_id: 1},
    { name: 'DS', vehicle_type_id: 1 },
    { name: 'EGYÉB', vehicle_type_id: 1 },
    { name: 'EGYEDI', vehicle_type_id: 1 },
    { name: 'ELECTROAUTO', vehicle_type_id: 1 },
    { name: 'EXCALIBUR', vehicle_type_id: 1 },
    { name: 'FERRARI', vehicle_type_id: 1 },
    { name: 'FIAT', vehicle_type_id: 1 },
    { name: 'FISKER', vehicle_type_id: 1 },
    { name: 'FORD', vehicle_type_id: 1 },
    { name: 'GAZ', vehicle_type_id: 1 },
    { name: 'GEO', vehicle_type_id: 1 },
    { name: 'GMC', vehicle_type_id: 1 },
    { name: 'GREAT WALL', vehicle_type_id: 1 },
    { name: 'GRECAV', vehicle_type_id: 1 },
    { name: 'HONDA', vehicle_type_id: 1 },
    { name: 'HUDSON', vehicle_type_id: 1 },
    { name: 'HUMMER', vehicle_type_id: 1 },
    { name: 'HYUNDAI', vehicle_type_id: 1 },
    { name: 'INFINITI', vehicle_type_id: 1 },
    { name: 'ISUZU', vehicle_type_id: 1 },
    { name: 'IVECO', vehicle_type_id: 1 },
    { name: 'JAGUAR', vehicle_type_id: 1 },
    { name: 'JDM', vehicle_type_id: 1 },
    { name: 'JEEP', vehicle_type_id: 1 },
    { name: 'KIA', vehicle_type_id: 1 },
    { name: 'LADA', vehicle_type_id: 1 },
    { name: 'LAMBORGHINI', vehicle_type_id: 1 },
    { name: 'LANCIA', vehicle_type_id: 1 },
    { name: 'LAND ROVER', vehicle_type_id: 1 },
    { name: 'LEVC', vehicle_type_id: 1 },
    { name: 'LEXUS', vehicle_type_id: 1 },
    { name: 'LIGIER', vehicle_type_id: 1 },
    { name: 'LINCOLN', vehicle_type_id: 1 },
    { name: 'LONDON', vehicle_type_id: 1 },
    { name: 'LOTUS', vehicle_type_id: 1 },
    { name: 'LTI (CARBODIES)', vehicle_type_id: 1 },
    { name: 'LUAZ', vehicle_type_id: 1},
    { name: 'MAHINDRA', vehicle_type_id: 1 },
    { name: 'MAN', vehicle_type_id: 1 },
    { name: 'MARUTI', vehicle_type_id: 1 },
    { name: 'MASERATI', vehicle_type_id: 1 },
    { name: 'MATRA', vehicle_type_id: 1 },
    { name: 'MAZDA', vehicle_type_id: 1 },
    { name: 'MCLAREN', vehicle_type_id: 1 },
    { name: 'MERCEDES-AMG' , vehicle_type_id: 1},
    { name: 'MERCEDES-BENZ' , vehicle_type_id: 1},
    { name: 'MERCEDES-MAYBACH' , vehicle_type_id: 1},
    { name: 'MERCURY', vehicle_type_id: 1 },
    { name: 'MG', vehicle_type_id: 1 },
    { name: 'MICROCAR', vehicle_type_id: 1 },
    { name: 'MINI', vehicle_type_id: 1 },
    { name: 'MITSUBISHI', vehicle_type_id: 1 },
    { name: 'MORRIS', vehicle_type_id: 1 },
    { name: 'MOSZKVICS', vehicle_type_id: 1 },
    { name: 'NISSAN', vehicle_type_id: 1 },
    { name: 'NSU', vehicle_type_id: 1 },
    { name: 'NYSA', vehicle_type_id: 1 },
    { name: 'OLDSMOBILE', vehicle_type_id: 1 },
    { name: 'OPEL', vehicle_type_id: 1 },
    { name: 'PEUGEOT', vehicle_type_id: 1 },
    { name: 'PIAGGIO', vehicle_type_id: 1 },
    { name: 'PLYMOUTH', vehicle_type_id: 1 },
    { name: 'POLSKI FIAT', vehicle_type_id: 1 },
    { name: 'PONTIAC', vehicle_type_id: 1 },
    { name: 'PORSCHE', vehicle_type_id: 1 },
    { name: 'PROTON', vehicle_type_id: 1 },
    { name: 'PULI', vehicle_type_id: 1 },
    { name: 'RELIANT', vehicle_type_id: 1 },
    { name: 'RENAULT', vehicle_type_id: 1 },
    { name: 'REPLIKA', vehicle_type_id: 1 },
    { name: 'ROLLS-ROYCE', vehicle_type_id: 1 },
    { name: 'ROVER' , vehicle_type_id: 1},
    { name: 'SAAB' , vehicle_type_id: 1},
    { name: 'SATURN' , vehicle_type_id: 1},
    { name: 'SEAT' , vehicle_type_id: 1},
    { name: 'SIMCA' , vehicle_type_id: 1},
    { name: 'SKODA' , vehicle_type_id: 1},
    { name: 'SMART', vehicle_type_id: 1 },
    { name: 'SSANGYONG', vehicle_type_id: 1 },
    { name: 'STEYR PUCH', vehicle_type_id: 1 },
    { name: 'SUBARU', vehicle_type_id: 1 },
    { name: 'SUZUKI', vehicle_type_id: 1 },
    { name: 'TALBOT', vehicle_type_id: 1 },
    { name: 'TATA', vehicle_type_id: 1 },
    { name: 'TATRA', vehicle_type_id: 1 },
    { name: 'TAVRIA', vehicle_type_id: 1 },
    { name: 'TESLA', vehicle_type_id: 1 },
    { name: 'TOYOTA', vehicle_type_id: 1 },
    { name: 'TRABANT', vehicle_type_id: 1 },
    { name: 'TRIUMPH', vehicle_type_id: 1 },
    { name: 'UAZ', vehicle_type_id: 1 },
    { name: 'VAUXHALL', vehicle_type_id: 1 },
    { name: 'VELOREX', vehicle_type_id: 1 },
    { name: 'VERSENYAUTÓ', vehicle_type_id: 1 },
    { name: 'VOLGA', vehicle_type_id: 1 },
    { name: 'VOLKSWAGEN', vehicle_type_id: 1 },
    { name: 'VOLVO', vehicle_type_id: 1 },
    { name: 'WARSZAWA', vehicle_type_id: 1 },
    { name: 'WARTBURG', vehicle_type_id: 1 },
    { name: 'WOLSELEY', vehicle_type_id: 1 },
    { name: 'YUGO', vehicle_type_id: 1 },
    { name: 'ZAPOROZSEC', vehicle_type_id: 1 },
    { name: 'ZASTAVA', vehicle_type_id: 1 },
    { name: 'ARO', vehicle_type_id: 2 },
    { name: 'BARKAS', vehicle_type_id: 2 },
    { name: 'BEDFORD', vehicle_type_id: 2 },
    { name: 'BIRDIE', vehicle_type_id: 2 },
    { name: 'CHEVROLET', vehicle_type_id: 2 },
    { name: 'CHRYSLER', vehicle_type_id: 2 },
    { name: 'CITROEN', vehicle_type_id: 2 },
    { name: 'DACIA', vehicle_type_id: 2 },
    { name: 'DAEWOO', vehicle_type_id: 2 },
    { name: 'DAIHATSU', vehicle_type_id: 2 },
    { name: 'DODGE', vehicle_type_id: 2 },
    { name: 'EGYÉB', vehicle_type_id: 2 },
    { name: 'ELECTROAUTO', vehicle_type_id: 2 },
    { name: 'FIAT', vehicle_type_id: 2 },
    { name: 'FORD', vehicle_type_id: 2 },
    { name: 'GAZ', vehicle_type_id: 2 },
    { name: 'GMC', vehicle_type_id: 2 },
    { name: 'GOUPIL', vehicle_type_id: 2 },
    { name: 'GRILLO', vehicle_type_id: 2 },
    { name: 'HONDA', vehicle_type_id: 2 },
    { name: 'HYUNDAI', vehicle_type_id: 2 },
    { name: 'ISUZU', vehicle_type_id: 2 },
    { name: 'IVECO', vehicle_type_id: 2 },
    { name: 'JIANGXI', vehicle_type_id: 2 },
    { name: 'KIA', vehicle_type_id: 2 },
    { name: 'LADA', vehicle_type_id: 2 },
    { name: 'LAND ROVER', vehicle_type_id: 2 },
    { name: 'LEXUS', vehicle_type_id: 2 },
    { name: 'LUBLIN', vehicle_type_id: 2 },
    { name: 'MAHINDRA', vehicle_type_id: 2 },
    { name: 'MAN', vehicle_type_id: 2 },
    { name: 'MAZDA', vehicle_type_id: 2 },
    { name: 'MEGA', vehicle_type_id: 2 },
    { name: 'MELEX', vehicle_type_id: 2 },
    { name: 'MERCEDES-BENZ', vehicle_type_id: 2 },
    { name: 'MICRO-VETT', vehicle_type_id: 2 },
    { name: 'MINI', vehicle_type_id: 2 },
    { name: 'MITSUBISHI', vehicle_type_id: 2 },
    { name: 'MULTICAR', vehicle_type_id: 2 },
    { name: 'NISSAN', vehicle_type_id: 2 },
    { name: 'OPEL', vehicle_type_id: 2 },
    { name: 'PEUGEOT', vehicle_type_id: 2 },
    { name: 'PIAGGIO', vehicle_type_id: 2 },
    { name: 'RENAULT', vehicle_type_id: 2 },
    { name: 'SEAT', vehicle_type_id: 2 },
    { name: 'SKODA', vehicle_type_id: 2 },
    { name: 'SSANGYONG', vehicle_type_id: 2 },
    { name: 'STEYR', vehicle_type_id: 2 },
    { name: 'SUZUKI', vehicle_type_id: 2 },
    { name: 'TATA', vehicle_type_id: 2 },
    { name: 'TOYOTA', vehicle_type_id: 2 },
    { name: 'UAZ', vehicle_type_id: 2 },
    { name: 'VAUXHALL', vehicle_type_id: 2 },
    { name: 'VOLKSWAGEN', vehicle_type_id: 2 },
    { name: 'YAMAHA', vehicle_type_id: 2 },
    { name: 'ZSUK', vehicle_type_id: 2 }
])
VehicleCategory.create([
   { name: 'Tehergépjármű', vehicle_type_id: 3 },
   { name: 'Kommunális gépjármű', vehicle_type_id: 3 },
   { name: 'Felépítmény, tartozék, adapter', vehicle_type_id: 3 }
  ])
